name: month_picker_dialog
description: Internationalized dialog for picking a single month from an infinite list of years.
version: 2.11.0
homepage: https://github.com/hmkrivoj/month_picker_dialog

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
